### ISSUE TITLE
"No module named Utils"

### ISSUE THREAD

**Issue by Leo152** [piroonj/cresil_nanocircle#6]
Hi, 
excuse me, I have a question for you.
What is the Utils module? "No module named Utils" is still displayed after using the command "pip install Utils".  

![image](https://user-images.githubusercontent.com/93251349/147634163-b2e6c071-fcfb-49d3-b15a-ed0c2024f154.png)

Best.

**Comment by piroonj** [comment]
Hi @Leo152 

@RAHenriksen has upload his Utils in link below.
https://github.com/piroonj/cresil_nanocircle/blob/master/NanoCircle/Utils.py

Thank you,
Piroon
