### ISSUE TITLE
CReSIL-identify  ValueError:too many values to unpack 

### ISSUE THREAD

**Issue by WeijiaSu** [piroonj/cresil_nanocircle#7]
Hi
I was trying to run the CreSil software for a nanopore eccDNA dataset. I got following error in the CReSIL-identify step :

"CReSIL-identify.py", line 346, in main
    (c, s, e) = node.split("_")
ValueError: too many values to unpack (expected 3)"

Do you have any suggestions on how to fix this?
Thank you so much
Weijia

**Comment by piroonj** [comment]
Hi Weijia,

We currently update the new version of CReSIL. Will keep you post once we release the new update.
The quick solution: If you have underscore “_” in the sample name, you my remove them or change to other character like “-“ or “.”.

Best regards,
Piroon

From: weijia su ***@***.***>
Date: Tuesday, 23 August BE 2565 04:29
To: piroonj/cresil_nanocircle ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [piroonj/cresil_nanocircle] CReSIL-identify ValueError:too many values to unpack (Issue #7)

Hi
I was trying to run the CreSil software for a nanopore eccDNA dataset. I got following error in the CReSIL-identify step :

"CReSIL-identify.py", line 346, in main
(c, s, e) = node.split("_")
ValueError: too many values to unpack (expected 3)"

Do you have any suggestions on how to fix this?
Thank you so much
Weijia

**Comment by WeijiaSu** [comment]
Thank you, Piroon, removing the underscore fixed the issue.
Weijia

**Comment by piroonj** [comment]
@WeijiaSu you should try the latest version of CReSIL.
https://github.com/visanuwan/cresil
